arch:
- amd64
- ppc64le
language: clojure
lein: 2.7.1
jdk:
- oraclejdk7
- openjdk7
script: ./ext/travisci/test.sh
notifications:
  email: false
  hipchat:
    rooms:
      - qiD4Yo5b7i1tz3kUW0ttsqoH0a1ZYVFihzThWtPT@322656
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view: %{compare_url}"
      - "Build details: %{build_url}"
